### ISSUE TITLE
Codes d'erreur inconsistants

### ISSUE THREAD

**Issue by mathieu-boutet-ulaval** [glo2003/H22-Iteration1#2]
Ces codes d'erreur sont différents de ceux dans l'énoncé principal:

https://github.com/glo2003/H22-Iteration1/blob/fb19e184b7312b63df7de7aa4c5d061391846006/features/1.seller-create.md#L47-L48

**Comment by mathieu-boutet-ulaval** [comment]
@vigenere23

**Comment by vigenere23** [comment]
En effet merci!

**Comment by vigenere23** [comment]
Corrigé dans l'énoncé principal ✅
